function irAlEnlace(identificador,imagen){let url='descargar.html?id='+encodeURIComponent(identificador);if(imagen)url+='&img='+encodeURIComponent(imagen);window.open(url,'_blank','noopener,noreferrer')}
function configurarSeccionConPaginacion(inputId,btnId,gridId,noResultsId,itemsPorPagina=30,nombreSeccion='juegos'){const searchInput=document.getElementById(inputId);const btnBuscar=document.getElementById(btnId);const grid=document.getElementById(gridId);const noResults=document.getElementById(noResultsId);if(!grid)return;const cards=Array.from(grid.querySelectorAll('.card'));let paginaActual=1;let terminoActual='';const paginacionFlotante=document.createElement('div');paginacionFlotante.className='paginacion-flotante';grid.parentNode.appendChild(paginacionFlotante);let sugerenciasBox=null;if(searchInput){sugerenciasBox=document.createElement('div');sugerenciasBox.className='sugerencias-box';searchInput.parentNode.appendChild(sugerenciasBox)}
function renderizarPagina(){const tarjetasFiltradas=cards.filter(card=>{const name=(card.getAttribute('data-name')||'').toLowerCase();return terminoActual===''||name.includes(terminoActual)});const totalTarjetas=tarjetasFiltradas.length;const totalPaginas=Math.ceil(totalTarjetas/itemsPorPagina)||1;if(paginaActual>totalPaginas)paginaActual=totalPaginas;if(paginaActual<1)paginaActual=1;const inicio=(paginaActual-1)*itemsPorPagina;const fin=inicio+itemsPorPagina;cards.forEach(card=>{const esDeBusqueda=tarjetasFiltradas.includes(card);const indexEnFiltradas=tarjetasFiltradas.indexOf(card);const enPaginaActual=indexEnFiltradas>=inicio&&indexEnFiltradas<fin;if(esDeBusqueda&&enPaginaActual){card.classList.remove('oculto-busqueda','oculto-pagina')}else{card.classList.add('oculto-pagina')}});if(noResults){noResults.style.display=(totalTarjetas===0)?'block':'none'}
renderizarControles(totalPaginas,totalTarjetas)}
function renderizarControles(totalPaginas,totalTarjetas){paginacionFlotante.innerHTML='';if(totalPaginas<=1||totalTarjetas===0){paginacionFlotante.classList.remove('activa');return}
paginacionFlotante.classList.add('activa');const btnAnterior=document.createElement('button');btnAnterior.className='btn-flotante-pag';btnAnterior.setAttribute('data-tooltip','Ir atrás');btnAnterior.setAttribute('title','Ir atrás');btnAnterior.setAttribute('aria-label','Ir atrás');btnAnterior.innerHTML=`
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
        <line x1="19" y1="12" x2="5" y2="12"></line>
        <polyline points="12 19 5 12 12 5"></polyline>
      </svg>
    `;if(paginaActual<=1){btnAnterior.style.opacity='0.3';btnAnterior.style.pointerEvents='none'}else{btnAnterior.style.opacity='1';btnAnterior.style.pointerEvents='auto';btnAnterior.onclick=()=>{paginaActual--;renderizarPagina()}}
paginacionFlotante.appendChild(btnAnterior);const btnSiguiente=document.createElement('button');btnSiguiente.className='btn-flotante-pag';btnSiguiente.setAttribute('data-tooltip',`Ver más ${nombreSeccion}`);btnSiguiente.setAttribute('title',`Ver más ${nombreSeccion}`);btnSiguiente.setAttribute('aria-label',`Ver más ${nombreSeccion}`);btnSiguiente.innerHTML=`
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
        <line x1="5" y1="12" x2="19" y2="12"></line>
        <polyline points="12 5 19 12 12 19"></polyline>
      </svg>
    `;if(paginaActual<=1){btnAnterior.style.opacity='0.3';btnAnterior.style.pointerEvents='none'}else{btnAnterior.style.opacity='1';btnAnterior.style.pointerEvents='auto';btnAnterior.onclick=()=>{paginaActual--;renderizarPagina();subirAlInicioGrid()}}
paginacionFlotante.appendChild(btnAnterior);if(paginaActual>=totalPaginas){btnSiguiente.style.opacity='0.3';btnSiguiente.style.pointerEvents='none'}else{btnSiguiente.style.opacity='1';btnSiguiente.style.pointerEvents='auto';btnSiguiente.onclick=()=>{paginaActual++;renderizarPagina();subirAlInicioGrid()}}
paginacionFlotante.appendChild(btnSiguiente)}
function subirAlInicioGrid(){const rect=grid.getBoundingClientRect();const scrollTop=window.pageYOffset||document.documentElement.scrollTop;window.scrollTo({top:scrollTop+rect.top-80,behavior:'auto'})}
function aplicarFiltro(termino){terminoActual=termino.toLowerCase().trim();paginaActual=1;renderizarPagina()}
if(searchInput&&sugerenciasBox){let debounceTimeout;searchInput.addEventListener('input',()=>{clearTimeout(debounceTimeout);debounceTimeout=setTimeout(()=>{const term=searchInput.value.toLowerCase().trim();sugerenciasBox.innerHTML='';if(term===''){sugerenciasBox.style.display='none';aplicarFiltro('');return}
let coincidenciasGuardadas=0;const fragment=document.createDocumentFragment();cards.forEach(card=>{const name=(card.getAttribute('data-name')||'');const nameLower=name.toLowerCase();if(nameLower.includes(term)&&coincidenciasGuardadas<5){const divSugerencia=document.createElement('div');divSugerencia.className='sugerencia-item';const regex=new RegExp(`(${term})`,"gi");divSugerencia.innerHTML=name.replace(regex,"<strong style='color:#ef4444;'>$1</strong>");divSugerencia.addEventListener('click',()=>{searchInput.value=name;sugerenciasBox.style.display='none';aplicarFiltro(name)});fragment.appendChild(divSugerencia);coincidenciasGuardadas++}});if(coincidenciasGuardadas>0){sugerenciasBox.appendChild(fragment);sugerenciasBox.style.display='block'}else{sugerenciasBox.style.display='none'}},300)});searchInput.addEventListener('keydown',(e)=>{if(e.key==='Enter'){clearTimeout(debounceTimeout);sugerenciasBox.style.display='none';aplicarFiltro(searchInput.value)}});if(btnBuscar){btnBuscar.addEventListener('click',()=>{clearTimeout(debounceTimeout);sugerenciasBox.style.display='none';aplicarFiltro(searchInput.value)})}
document.addEventListener('click',(e)=>{if(e.target!==searchInput&&e.target!==sugerenciasBox){sugerenciasBox.style.display='none'}})}
renderizarPagina()}
const btnSubir=document.getElementById("btnSubir");let scrollRendering=!1;window.addEventListener('scroll',()=>{if(!scrollRendering){window.requestAnimationFrame(()=>{const scrolled=window.scrollY>200;if(btnSubir){btnSubir.style.display=scrolled?"flex":"none"}
document.body.classList.toggle("scrolled-down",scrolled);scrollRendering=!1});scrollRendering=!0}},{passive:!0});function subirArriba(){window.scrollTo({top:0,behavior:"smooth"})}
document.addEventListener('DOMContentLoaded',()=>{configurarSeccionConPaginacion('searchProgramas','btnSearchProgramas','programas-grid','noResultsProgramas',28,'programas');configurarSeccionConPaginacion('searchJuegos','btnSearchJuegos','juegos-grid','noResultsJuegos',28,'juegos');configurarSeccionConPaginacion('searchWindows','btnSearchWindows','windows-grid','noResultsWindows',28,'Windows')});fetch('requisitos.json').then(res=>{if(res.ok)console.log("Archivo requisitos.json pre-cargado con éxito para mayor velocidad.");}).catch(err=>console.error("Error al intentar pre-cargar requisitos.json:",err))
